### ISSUE TITLE
Cannot `npm install es6-shim` on Ubuntu 12.04.5 LTS

### ISSUE THREAD

**Issue by sivabudh** [paulmillr/es6-shim#395]
Hello,

I tried to npm install the package on Ubuntu 12.04.5, but it failed. I tried on Ubuntu 14.04, and didn't run into any problems.

Am I doing something wrong?

Thanks!

```
root@angular2-quickstart:~/Code# npm install es6-shim
npm http GET https://registry.npmjs.org/es6-shim

npm ERR! Error: failed to fetch from registry: es6-shim
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /root/Code/npm-debug.log npm
npm ERR!
npm ERR! System Linux 3.13.0-71-generic
npm ERR! command "node" "/usr/bin/npm" "install" "es6-shim"
npm ERR! cwd /root/Code
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: es6-shim
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/Code/npm-debug.log
npm not ok
```

**Comment by ljharb** [comment]
That's a network error. Since you're using an *ancient* node, 0.6, and an equally ancient and unsupported `npm`, the 1.x series, you'll need to upgrade npm to 2.x at least, and you'll want to upgrade node to v4 or v5.
